### ISSUE TITLE
Do not hide on scroll if parent view content size less than viewport

### ISSUE THREAD

**Issue by romanr** [Friend-LGA/LGPlusButtonsView#10]
There is a UX issue when your scroll view content size is smaller or equal to viewport. 
For example Table view with no rows or only couple of rows. User pulls the Scroll/Table view and view bounces, scroll event fires and button disappears.
Plus button in this case must stay on screen to allow user to add items. 
- There is no need to hide Plus button since scroll view is empty and user will need to use this button anyway to add content.
- User may not know how to get the Plus button back. They need to pull/drag the empty scroll view to make it appear. The Plus button pattern is about letting user discover the Plus button by scrolling the content and learn how to get the Plus button to display this way
- It is then reported by user as a bug , "Cannot add new items" during the user testing.
- And finally, take a look at Googles Inbox app, that's how it works there - the Plus button stays on screen and does not hide automatically when there's no content to scroll.

**Comment by Friend-LGA** [comment]
Ok, I can add new property something like `notHideWhenContentSizeIsSmollerThanFrame`, but do we really need it?
If you want to make it like "Google Inbox App", why you didn't set `plusButtonView.alwaysVisible = YES;`? It should solve your problem.
Or if you want to hide it when user add some content, you can check contentSize when user add this content and just set again `plusButtonView.alwaysVisible = NO;`

**Comment by romanr** [comment]
I think the LGPlusButtonsView should check in didScroll event if "content is smaller than frame". no need to have separate property notHideWhenContentSizeIsSmallerThanFrame because it should be a standard behaviour.

Yes, as a workaround we could check every time when content added or removed, but then will also need to check when device orientation changed, etc. Basically it will require writing a lot of workarounds for the case this component should check internally.
Much easier to check in one place , inside LGPlusButtonsView didScroll handler.

**Comment by Friend-LGA** [comment]
Ok, I will think about It

**Comment by Friend-LGA** [comment]
Fixed: https://github.com/Friend-LGA/LGPlusButtonsView/commit/f2eb308e2af957d753b541aefa9bd07f1ffebe01
