### ISSUE TITLE
Podfile and Schemes is missing in Demo

### ISSUE THREAD

**Issue by romanr** [Friend-LGA/LGPlusButtonsView#11]
Looks like accidentally removed in 1.0.7

**Comment by Friend-LGA** [comment]
Yes, it was removed, but it works fine, I checked it right now on different PC. Just remove and download it again.

**Comment by romanr** [comment]
If you reset and re-download, the Podfile does not appear. It is missing in git repo.
You cannot run "pod update" in Demo.
Also cannot run any targets in Demo project.

**Comment by Friend-LGA** [comment]
Demo project no more contains cocoapods. It works fine. Repeat, I just now check it on different PC, download repository and launch demo project and it works. I newer launch it here, and it works.

**Comment by romanr** [comment]
The confusion is because Demo contains XCworkspace which is not actual anymore.
Need to remove XCWorkspace form the demo.

**Comment by Friend-LGA** [comment]
Give me link on this file and I will remove it.

Like: https://github.com/Friend-LGA/LGPlusButtonsView/tree/master/Demo/LGPlusButtonsViewDemo.xcodeproj
