### ISSUE TITLE
Example/demo of images in buttons

### ISSUE THREAD

**Issue by romanr** [Friend-LGA/LGPlusButtonsView#12]
No matter what I try buttons always come up with blank face without assigned images.

```
[_plusButtonsView setButtonsImages:@[[UIImage imageNamed:@"add-symbol"],[UIImage imageNamed:@"calendar-1"],[UIImage imageNamed:@"calendar-1"],[UIImage imageNamed:@"calendar-1"]] forState:UIControlStateNormal];
```

![image](https://cloud.githubusercontent.com/assets/329079/11134585/cfe230f0-8952-11e5-9fe4-4f434a94777f.png)

Are there any special requirements about images, like they have to be particular dimensions?
Will be great if we ca have Demo to include some example with images.

**Comment by Friend-LGA** [comment]
Right now in demo I use images to show circle buttons, check it out, please.

**Comment by Friend-LGA** [comment]
Fixed: https://github.com/Friend-LGA/LGPlusButtonsView/commit/f2eb308e2af957d753b541aefa9bd07f1ffebe01
