### ISSUE TITLE
Option to have background overlay

### ISSUE THREAD

**Issue by romanr** [Friend-LGA/LGPlusButtonsView#14]
Like in Material design it's essential have option to have app screen covered with transparent white or blur overlay when button is tapped. (https://www.google.com/design/spec/components/buttons-floating-action-button.html)
This lets user easily focus on buttons and separate buttons from content.
Tapping on overlay hides the buttons and overlay.

**Comment by Friend-LGA** [comment]
Yeah, coming soon in next update

**Comment by romanr** [comment]
:+1: :bow:

**Comment by Friend-LGA** [comment]
Fixed: https://github.com/Friend-LGA/LGPlusButtonsView/commit/f2eb308e2af957d753b541aefa9bd07f1ffebe01
