### ISSUE TITLE
Shadow rotates together with button graphics. Shadow needs to be property of LGPlusButtonsView.

### ISSUE THREAD

**Issue by romanr** [Friend-LGA/LGPlusButtonsView#15]
Try to set Shadow offset to non-centered value on Y scale, e.g.

```
  UIImage *circleImageNormal = [LGDrawer drawEllipseWithImageSize:
  ....
  shadowOffset:CGPointMake(0, 2);
  shadowBlur:shadowBlur];
  [_plusButtonsView setButtonsImage:circleImageNormal forState:UIControlStateNormal];
```

![image](https://cloud.githubusercontent.com/assets/329079/11208114/1d5f0046-8cce-11e5-9ddd-bf3176ceb8a1.png)

When Plus button is pressed the shadow rotates 45 degrees with it:

![image](https://cloud.githubusercontent.com/assets/329079/11208128/2de31fd8-8cce-11e5-9df5-8072265de190.png)

Therefore button graphics shadow works only if it's perfectly centered.

Shadow needs to be property of LGPlusButtonsView, not part of button graphics.
e.g.

```
_plusButtonsView.shadowOffset=
_plusButtonsView.shadowColor=
_plusButtonsView.shadowBlur=
```

**Comment by Friend-LGA** [comment]
Yes, it's bug, I will fix it

**Comment by Friend-LGA** [comment]
Fixed: https://github.com/Friend-LGA/LGPlusButtonsView/commit/f2eb308e2af957d753b541aefa9bd07f1ffebe01
