### ISSUE TITLE
Cannot trigger touch event inside the Plus Button showing area

### ISSUE THREAD

**Issue by johnny51925** [Friend-LGA/LGPlusButtonsView#16]
![screen shot 2015-11-18 at 3 03 49 pm](https://cloud.githubusercontent.com/assets/8379957/11234721/cb876248-8e05-11e5-8c2a-225c3e94e92c.png)
As you see the first image I can click the "asd" button in the scroll view WHICH is not in the Plus buttons showing area

![screen shot 2015-11-18 at 3 04 13 pm](https://cloud.githubusercontent.com/assets/8379957/11234740/e73e8a70-8e05-11e5-9fd1-520699549ea4.png)
![screen shot 2015-11-18 at 3 04 09 pm](https://cloud.githubusercontent.com/assets/8379957/11234741/e766d66a-8e05-11e5-8730-73af1728a280.png)

But when I scroll to the showing area, the touch event doesn't response

**Comment by Friend-LGA** [comment]
I'm working on a big update right now, it will be done in a few days, most of problems will be solved.

**Comment by romanr** [comment]
I just came to report same issue.
when Plus button is collapsed the area above it don't pass through touches:

![image](https://cloud.githubusercontent.com/assets/329079/11314524/12778a2a-8f9b-11e5-87dd-7dd0a0a85b89.png)

**Comment by Friend-LGA** [comment]
Fixed: https://github.com/Friend-LGA/LGPlusButtonsView/commit/f2eb308e2af957d753b541aefa9bd07f1ffebe01
