### ISSUE TITLE
Changing the position of the LGPlusButtonView

### ISSUE THREAD

**Issue by ferologics** [Friend-LGA/LGPlusButtonsView#2]
I'm trying to implement this in my project, but when I use it with UIView the buttons paper in the topright corner his is correct but I need to display them under the toprightcorner

How can I inset or change the position of the buttons programmatically? (one way is to create a uview with size 1x1 and link it to that but that's not pretty)

I can't really access the source

**Comment by Friend-LGA** [comment]
Try to change

``` objective-c
plusButtonView.position = LGPlusButtonsViewPositionTopRight;
```

Otherwise if you want to set more specific position you can use

``` objective-c
plusButtonView.contentInset = UIEdgeInsets(...);
plusButtonView.buttonInset = UIEdgeInsets(...);
```

**Comment by ferologics** [comment]
well, isn't the content inset between every button??  I have it set to the LGPlusButtonsViewPositionTopRight, that's the problem

**Comment by Friend-LGA** [comment]
``` objective-c
plusButtonView.buttonInset = UIEdgeInsets(...); // it makes insets between buttons
plusButtonView.contentInset = UIEdgeInsets(...); // it makes insets around all buttons
```

Try it:

``` objective-c
plusButtonsView.contentInset = UIEdgeInsetsMake(50.f, 0.f, 0.f, 0.f);
```

<img src="https://cloud.githubusercontent.com/assets/5897136/8939700/a66d4012-356e-11e5-8b6f-13266bd54900.png" width="230"/>

**Comment by ferologics** [comment]
plusButtonsView.contentInset = UIEdgeInsetsMake(50.f, 0.f, 0.f, 0.f);

well, that works but when you try to tap the button which unwinds the whole view it's blocked because the actual view starts at the same position as before the inset. It's just contentInset, I need the whole view inset :/

**Comment by Friend-LGA** [comment]
Ok... now I think I understand you. But what the reason? Do you want to make buttons appear at the middle of the screen? I will try to add offset property at evening.

**Comment by ferologics** [comment]
I want them to be at the same-ish position as in the photo that you added here,
under the trigger button which will be used to open and close the plusButtonView

**Comment by Friend-LGA** [comment]
Now you can use `plusButtonsView.offset = CGPointMake(0.f, 50.f)` to change position

**Comment by ferologics** [comment]
THANKS! this is such a great pod, can't be grateful enough

**Comment by Friend-LGA** [comment]
:+1:
