### ISSUE TITLE
Setting all buttons to same size produces unwanted offset

### ISSUE THREAD

**Issue by romanr** [Friend-LGA/LGPlusButtonsView#21]
If button 0 is not larger than other buttons, unwanted offset is introduced.

How to reproduce:
Do not set larger size for buttonAtIndex:0
comment out in Demo project `PlusViewController.m:84`

```
    [_plusButtonsViewMain setButtonAtIndex:0 size:CGSizeMake(56.f, 56.f)
```

to

```
//     [_plusButtonsViewMain setButtonAtIndex:0 size:CGSizeMake(56.f, 56.f)
```

Result : buttons 1-3 have unwanted offset left relative to button 0:

![image](https://cloud.githubusercontent.com/assets/329079/12078922/acae8b66-b278-11e5-8723-99dc412aaf6f.png)

**Comment by Friend-LGA** [comment]
Because of this:

``` objective-c
for (NSUInteger i=1; i<=3; i++)
    [_plusButtonsViewMain setButtonAtIndex:i offset:CGPointMake(-6.f, 0.f)
                            forOrientation:(UI_USER_INTERFACE_IDIOM() == UIUserInterfaceIdiomPhone ? LGPlusButtonsViewOrientationPortrait : LGPlusButtonsViewOrientationAll)];
```

PlusScrollViewController.m:107

I wrote this to place small buttons on center.
