### ISSUE TITLE
How can i add button whereever i want?

### ISSUE THREAD

**Issue by yigit26** [Friend-LGA/LGPlusButtonsView#29]
Hi, 
I want to add a floating button somewhere in the view.  There are only 4 options. 
-LGPlusButtonsViewPositionBottomRight
-LGPlusButtonsViewPositionBottomLeft
-LGPlusButtonsViewPositionTopRight
-LGPlusButtonsViewPositionTopLeft 
I need to add button at the point-for example : CGPointMake(100, 100)-.Is there any
solition for this   situation.

Best Regards,
Yigit.

![screen shot 2016-06-22 at 11 46 54](https://cloud.githubusercontent.com/assets/4510936/16260466/44763f52-3870-11e6-80ce-da74af979579.png)

**Comment by ericwastaken** [comment]
Create a view and place that view wherever you want the LGPlusButtonsView to show up.

```
// Create a placeholder view for our Action Button
let actionButtonContainerView = UIView()
self.view.addSubview(actionButtonContainerView)
// Use constraints to place your container view exactly as you wish
```

Now, create the LGPlusButtonsView and add it to the container view

```
// Create your buttons view
actionButton = LGPlusButtonsView(numberOfButtons: 3, firstButtonIsPlusButton: true, showAfterInit: true)
// Set it up any way you wish

// Once done setting it up, add to the container!
actionButtonContainerView.addSubview(actionButton)
// Don't forget to constrain actionButton here also (something like CENTERX CENTERY in your super view)
```

**Comment by yigit26** [comment]
Thanks
