### ISSUE TITLE
How can I adjust the sensitive of scrollview to hide/show the button

### ISSUE THREAD

**Issue by johnny51925** [Friend-LGA/LGPlusButtonsView#8]
As the coding written now,
I need to scroll for a short distance in order to show/hide the button

Is there any method to change the sensitivity of the button 
(just like the offsetY swipe for 5.0f to hide/show)

Thank You

**Comment by Friend-LGA** [comment]
No way right now. I will add it in few days.

**Comment by Friend-LGA** [comment]
Use `plusButtonsView.scrollSensitivity = 20.f;`
