### ISSUE TITLE
Collapse on scroll

### ISSUE THREAD

**Issue by romanr** [Friend-LGA/LGPlusButtonsView#9]
The button does not collapse on scroll. The opened buttons stay open. I could not find how to make them hide. Am I missing something?
If it's not built-in function, this is a significant UX problem. Nobody ever need those buttons stay open while parent view is scrolling. I think such functionality should be part of LGPlusButtons rather than coding manually hooking up to scroll event.

**Comment by Friend-LGA** [comment]
Just open and run demo project. Everything works fine.
If you make it in the same way and it still does not working, then show me your code.

**Comment by romanr** [comment]
Thank you. I am referring to the Demo.

How to reproduce:
1. Clone repo from github
2. Run the Demo
3. select "UIScrollView + Variant 2"
4. tap button to expand. - Buttons expand
5. scroll up - buttons move out of view
6. scroll down - expanded buttons move into the view

At step 5 the buttons should collapse.
User switched their attention to other activity by scrolling the parent view. Therefore buttons now obstruct user's view.

**Comment by Friend-LGA** [comment]
Ok, I understand you. I will fix it today or tomorrow.

**Comment by Friend-LGA** [comment]
Use `plusButtonsView.hideButtonsOnScroll = YES;`
